### ISSUE TITLE
Delete a Wishlist

### ISSUE THREAD

**Issue by tpranav111** [CSCI-GA-2820-FA24-003/wishlists#10]
As a customer
I need to delete the entire wishlist  
So that I can easily remove all items from the wishlist at once, instead of having to delete them one by one.
   
 ### Details and Assumptions
 * A wishlist may or may not contain any items, hence, allowing the user to delete it. 
 * Once deleted, the user gets a confirmation about the same and wishlist details are deleted from the database.
 * If the wishlist is not empty, individual items from the wishlist are first cleared. 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a valid wishlist ID, 
 When customer requests to delete it
 Then all items inside the wishlist are first deleted and then the wishlist itself. 
```

**Comment by James-Studio** [comment]
I created another branch to resolve the conflict issues caused by changes in the file hierarchy.
