### ISSUE TITLE
Create a new item in a wishlist

### ISSUE THREAD

**Issue by ProgrammerManstein** [CSCI-GA-2820-FA24-003/wishlists#2]
**As a** customer
**I need** add a product to my wishlist using the wishlistsID, product ID, quantity,
**So that** [benefit]  I can collect the products that I wish I had the money to purchase.
   
 ### Details and Assumptions
 * [document what you know]
A customer might have multiple wishlists, so they should add  product to a specific wishlist(ID).
A customer has multiple wishlists associated with their customer ID.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a product is already in the wishlist,
 When the customer adds the same product
 Then the quantity of the product is updated in the wishlist.

 Given a wishlist is exist,
 When the customer adds a product by wishlist ID, product ID, and quantity
 Then the product is added to the wishlist.
```

**Comment by James-Studio** [comment]
The label can be set to "enhancement"

**Comment by Geralt5** [comment]
Create a new item in a wishlist
