### ISSUE TITLE
List All Items in a Wishlist

### ISSUE THREAD

**Issue by sc10355** [CSCI-GA-2820-FA24-003/wishlists#3]
**As a** Customer
**I need** the ability to view all items in a specific wishlist
**So that** I can manage and plan purchases from the collections I have created
   
 ### Details and Assumptions
- The function should allow me to see every item listed in the chosen wishlist.
- Each item should show relevant details such as product name and quantity.
- API:  ``` GET    /wishlists/{id}/items       <- List all items in a wishlist ```
   
 ### Acceptance Criteria  
   
 ```gherkin
Given I have selected a specific wishlist with a valid wishlist ID and it contains items,
When I request to see all items in this wishlist,
Then the system should display all items along with their details.
```
 ```gherkin
Given I have selected a wishlist that is empty or the wishlist ID is invalid,
When I request to see all items in this wishlist,
Then the system should inform me that there are no items in this wishlist.
```

**Comment by James-Studio** [comment]
The label can be set to "enhancement"

**Comment by sc10355** [comment]
> The label can be set to "enhancement"

Thanks for the reminder, but how should I add the label?

**Comment by James-Studio** [comment]
My enhancement label automatically appeared when the new issue was created, but I am not sure how to change the label into other labels actually. Maybe I will ask CA in the Slack.

**Comment by sc10355** [comment]
> My enhancement label automatically appeared when the new issue was created, but I am not sure how to change the label into other labels actually. Maybe I will ask CA in the Slack.

I just created a new issue, but the 'enhancement' label didn’t show up automatically. I’m also not sure how to add the label manually. If you find out how to fix it, please let me know!

**Comment by Geralt5** [comment]
Read an item from a wishlist issue
