### ISSUE TITLE
Delete an item in Wishlist

### ISSUE THREAD

**Issue by ProgrammerManstein** [CSCI-GA-2820-FA24-003/wishlists#4]
**As a** [role]customer
**I need** [function]to remove a item/product from my wishlist using the wishlistsID, product ID,
**So that** [benefit] I can remove the item/products I no longer wish to purchase.
   
 ### Details and Assumptions
 * [document what you know]
A customer might have multiple wishlists, so they should remove a product from a specific wishlist(ID).
A customer has multiple wishlists associated with their customer ID.

 ### Acceptance Criteria  
   
 ```gherkin
 Given [some context]the product exists in the wishlist,
 When [action taken]the customer want to remove the product,
 Then [outcome observed]the product is removed, and no longer exist in the wishlist.
 Given [some context]the product doesn't exists in the wishlist,
 When [action taken]the customer want to remove the product,
 Then [outcome observed]nothing will happen. No error message or opporation in the database is needed.
```

**Comment by James-Studio** [comment]
The label can be set to "enhancement"
