### ISSUE TITLE
Add Query String to List Route

### ISSUE THREAD

**Issue by ProgrammerManstein** [CSCI-GA-2820-FA24-003/wishlists#47]
**As a** customer
**I need**  filter the items within a wishlist using query parameters
**So that** I can get a subset of items based on specific attributes
   
 ### Details and Assumptions
 * The List method should allow to filter the items with the following attributes: (1) category (2) price
 * The results should be the filtered products which has specific attributes only
 ### Acceptance Criteria  
   
 ```gherkin
 Given an item and an attribute exists
 When I send a request with a query string (e.g., ?category=food)
 Then it only shows the items that match the query string.
```

**Comment by James-Studio** [comment]
The issue is quite general. Need to describe it more specifically.
